# This YAML is where we manage GitHub labels as code for the issue tracker.

## The basics
- name: bug
  description: "Something isn't working"
  color: "d73a4a"
- name: documentation
  description: Improvements or additions to the documentation, especially on the wiki and contributing guidelines.
  color: "0075ca"
- name: duplicate
  description: This issue or patch/merge request already exists
  color: "cfd3d7"
- name: enhancement
  description: New feature or request
  color: "a2eeef"
- name: good first issue
  description: Good for first-time contributors
  color: "7057ff"
- name: help wanted
  description: Extra attention and assistance required
  color: "008672"
- name: invalid
  description: "This doesn't seem right"
  color: "e4e669"
- name: missing info
  #from_name: question
  description: Further information is requested
  color: "d876e3"
- name: wontfix
  description: THis will not be worked on
  color: "ffffff"
- name: upstream
  description: The issue is being flagged on or imported/copied from upstream.
  color: "ededed"

# project specifics
- name: hackclub
  #from_name: hackclub-arcade
  color: "ec3750"
  description: Issues relating to Hack Club, its YSWS and related projects/programs, and HCB.
- name: open-source
  color: "ffffff"
  descriptions: Issues relating to open-source work and projects.
- name: recaptime-dev
  description: "Issues relating to RecapTime.dev and its projects (including Community Lorebooks)"
  color: "ededed"

# school related
- name: school
  color: "ffc107"
  description: "Issues relating to schoolworks and academic life"
- name: cs50x
  color: "d41c0f"
  description: "Issues relating to the CS50x course from Harvard on edX"

# misc
- name: personal-stuff
  description: "Issues relating to personal life (DO NOT LEAK SENSTIVE INFO)"
  color: "ededed"
- name: blog
  description: "Issues relating to the blog, including blog posts and its underlying infrastructure/code that runs it"
  color: "ededed"

## GitHub issue form identifiers
- name: 'gh-issue-form: default'
  description: "[FOR TRIAGEOPS ONLY - DO NOT REMOVE] Issues made using the default form"
  color: "8D7471"
- name: 'gh-issue-form: access-requests'
  description: "[FOR TRIAGEOPS ONLY - DO NOT REMOVE] Issues made using the access request form"
  color: "8D7471"
- name: "gh-issue-form: public-inbox"
  description: "[FOR TRIAGEOPS ONLY - DO NOT REMOVE] Public inbox-styled threads"
  color: "8D7471"
- name: "gh-issue-form: blog"
  description: "[FOR TRIAGEOPS ONLY - DO NOT REMOVE] Issues related to the blog"
  color: "8D7471"

## TODO: Import labels from sourcehut todo and JetBrains YouTrack/Space Cloud counterparts.
