# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
name: Default issue form for everything
description: We use this issue form to easily triage things for our TriageOps GitHub Actions workflow and as an all-around way of filling issues and tasks.
title: a descriptive but short title here
labels:
  - 'gh-issue-form: default'
assignees: [ajhalili2006]
body:
  - type: markdown
    attributes:
      value: >-
        # Default GitHub issue form - instructions for use

        @ajhalili2006's public issue tracker in GitHub is used to track work and todos, alongside a lot of automation work using GitHub Actions and webhooks behind the scenes and being his public inbox for those who don't like sending plain text emails. 
        
        
        > [!NOTE]
        > Please see [this page](https://wiki.andreijiroh.dev/meta/issue-tracker/github) on his wiki for more detailed guidance. Note that issues filed here will be synchronized to other places (i.e. GitLab and sourcehut), including edits to the issue description and title, label and status changes. Comments and replies are not synchronized for the time being due to API rate limits (especially to ensure the stability of sourcehut infrastructure).

        ## General guidelines

        _See [the contributing guidelines for the full instructions](https://github.com/andreijiroh-dev/personal-launchpad/blob/main/CONTRIBUTING.md), alongside the wiki page linked above._
        * Do not file vulnerability reports publicly here. Visit <https://andreijiroh.dev/contact/security> and the project-specific security policy for instructions.
        * If a project has its issue tracker, please use it instead to avoid inconvenience to the maintainers.
        * [Search][search-link] for any duplicates first and subscribe to that issue instead unless the issue is different.

        ## Preflight Checks

        [Search across Anrei Jiroh's GitHub repositories][search-link] for any duplicates before continuing. You must tick the dupe check, alongside the agreement to the [Community Code of Conduct][coc], otherwise you are blocked from submitting the issue.

        ### Issue types

        The issue type is used on both the TriageOps workflow in GitHub Actions and in our own webhook-based automations (including issue sync) on things like labeling and project assignments.

        ### About this Issue

        This text area is where you write the main thing. Feel free to attach logs and device info here for webapps. If you are also attaching HAR logs, please [use HAR Sanitizer](https://har-sanitizer.pages.dev/) to avoid API key leakage.

        ## Additional/Related Resources

        This is optional and you can skip ahead if none. Feel free to add one by editing the issue description. Mostly used for linking related content like issues and docs.

        [search-link]: https://github.com/issues?q=org%3Aandreijiroh-dev%20org%3Aandreijirohdev-labs%20org%3Aajhalili2006-archive%20user%3Aajhalili2006
        [coc]: https://policies.recaptime.dev/code-of-conduct
  - type: checkboxes
    id: dupe_checks
    attributes:
      label: Preflight Checks
      options:
        - label: "I have [searched issues across Andrei Jiroh's GitHub repositories](https://github.com/issues?q=org%3Aandreijiroh-dev%20org%3Aandreijirohdev-labs%20org%3Aajhalili2006-archive%20user%3Aajhalili2006), and there are no duplicates found."
          required: true
        - label: "I agree to the [Recap Time Squd Community Code of Conduct](https://policies.recaptime.dev/code-of-conduct)."
          required: true
  - type: dropdown
    id: type
    attributes:
      label: What type of issue does this ticket fall under?
      description: >-
        This is used by our labeler job in the TriageOps workflow and GitHub project automations to help label things and to allow us to keep things tidy.
      options:
        - personal-stuff
        - school
        - cs50x
        - recaptime.dev
        - community
        - open-source
        - multifandom
        - hackclub
    validations:
      required: true
  - type: textarea
    id: about_this_issue
    attributes:
      label: About this issue
      description: Please describe as many details as possible here.
    validations:
      required: true
  - type: textarea
    id: resources
    attributes:
      label: Prior Art / Additional/Related Resources
      description: Links to related issues and resources.
  - type: dropdown
    id: project
    attributes:
      label: "Is this issue related to one of ~ajhalili2006's project?"
      description: "Your issue might be moved/copied into the respective project's issue tracker on your behalf. Note that the list only includes projects that Andrei Jiroh currently maintains, excluding external and Recap Time Squad-related projects."
      multiple: true
      options:
        - dotfiles
        - nixops-config
        - website
        - wiki
        - docker-images
        - ppa
        - mirrors-cdn
        - api-servers
        - scripts-toolkit
        - infraops
        - donatetgbot
        - None of the above
  - type: markdown
    attributes:
      value: >
        ---

        _This issue form was made with help from [Issue Forms Creator](https://issue-forms-creator.netlify.app)._
