name: Default issue form for everything
description: >-
  We use this issue form to easily triage things for our TriageOps GitHub
  Actions workflow.
title: an descriptive but short title here
labels:
  - 'gh-issue-form: default'
body:
  - type: markdown
    attributes:
      value: >-
        # Default GitHub issue form - instructions for use

        @ajhalili2006's public issue tracker in GitHub is used to track work and
        todos, alongside a lot of automation work using GitHub Actions and
        webhooks behind the scenes. Please see [this
        page](https://wiki.andreijiroh.xyz/meta/issue-tracker/github) on his
        wiki for more detailed guidance.

        Note that issues filed here will be synchorized to GitLab, sourcehut and
        JetBrains YouTrack counterparts, including edits to the issue
        description and title, label and status changes. Comments and replies
        are not synchronized for the time being due to API rate limits
        (especially to ensure the stability of sourcehut infrastructure).

        ## General guidelines

        _See [the contributing guidelines for the full
        instructions](https://github.com/andreijiroh-dev/personal-launchpad/blob/main/CONTRIBUTING.md),
        alongside the wiki page linked above._

        * Do not file vulnerability reports publicly here. Visit
        <https://andreijiroh.xyz/contact/security> and project-specific security
        policy for instructions.

        * If a project has its own issue tracker, please use it instead to avoid
        inconvenience to the maintainers.

        *
        [Search](https://github.com/issues?q=org%3Aandreijiroh-dev+user%3Aajhalili2006+)
        for any duplicates first and subscribe to that issue instead unless the
        issue is different.

        ## Preflight Checks

        [Search across Anrei Jiroh's GitHub
        repositories](https://github.com/issues?q=org%3Aandreijiroh-dev+user%3Aajhalili2006+)
        for any duplicates before continuing. You must tick the dupe check,
        alongside the agreement to the [Community Code of
        Conduct](https://go.andreijiroh.xyz/coc), otherwise you are blocked from
        submitting the issue.


        ### Issue types

        The issue type is used on both the TriageOps workflow in GitHub Actions
        and in our own webhook-based automations (including issue sync) on
        things like labeling and project assignments.

        ### About this Issue


        This textarea is where you write the main thing. Feel free to attach
        logs and device info here for webapps. If you are also attaching HAR logs,
        please [use HAR Sanitizer](https://har-sanitizer.pages.dev/) to avoid
        API key leakage.

        ## Additional/Related Resources

        This is optional and you can skip ahead if none. Feel free to add one by
        editing the issue description.
  - type: checkboxes
    id: dupe_checks
    attributes:
      label: Preflight Checks
      options:
        - label: >-
            I have [searched issues across Anrei Jiroh's GitHub
            repositories](https://github.com/issues?q=org%3Aandreijiroh-dev+user%3Aajhalili2006+)
            and there are no duplicates found.
          required: true
        - label: >-
            I agree to the [Community Code of Conduct](https://go.andreijiroh.xyz/coc).
          required: true
  - type: dropdown
    id: type
    attributes:
      label: What type of issue this ticket should fall under?
      description: >-
        This is used by our labeler job in TriageOps workflow and GitHub project
        automations to help label things and to allow us to keep things tidy.
      options:
        - personal-stuff
        - school
        - recaptime.dev
        - community
        - open-source
        - multifandom
        - hackclub-acrade
    validations:
      required: true
  - type: textarea
    id: about_this_issue
    attributes:
      label: About this issue
      description: Please describe as much details as possible here.
    validations:
      required: true
  - type: textarea
    id: resources
    attributes:
      label: Prior Art / Additional/Related Resources
      description: Links to related issues and resources.
  - type: dropdown
    id: project
    attributes:
      label: Is this issue related to one of ~ajhalili2006's project?
      description: >-
        Your issue might be moved/copied into respective project's issue
        tracker. Note that the list only include projects that Andrei Jiroh
        currently maintains, excluding external and Recap Time Squad-related
        projects.
      multiple: true
      options:
        - dotfiles-modern
        - dotfiles-legacy
        - website
        - wiki
        - docker-images
        - ppa
        - mirrors-cdn
        - api-servers
        - scripts-toolkit
        - donatetgbot
        - None of the above
  - type: markdown
    attributes:
      value: >
        ---

        _This issue form was generated with help from [Issue Forms
        Creator](https://issue-forms-creator.netlify.app)_
