name: TriageOps - Labels Manager

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/labels.yml'
      - '.github/workflows/labels.yml'

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.GH_RTDEV_APP_CLIENT_ID }}
          private-key: ${{ secrets.GH_RTDEV_APP_KEY }}
      - name: Sync labels using config
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          yaml-file: .github/labels.yml
          dry-run: ${{ github.event_name == 'pull_request' }}
          exclude: |
            help*
            *issue