name: TriageOps - Labels Manager

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/labels.yml'
      - '.github/workflows/labels.yml'

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download .env.ci from central repo
        run: wget -O .env.ci https://github.com/andreijiroh-dev/dotenvx-secretstore/raw/main/.env.ci
      - name: Load secrets via dotenvx
        uses: andreijiroh-dev/dotenvx-action@main
        with:
          path: .env.ci
          key: ${{ secrets.DOTENV_META_SECRETS_KEY_CI }}
        id: dotenvx
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ steps.dotenvx.outputs.GH_APP_ID }}
          private-key: ${{ steps.dotenvx.outputs.GH_APP_KEY }}
      - name: Sync labels using config
        uses: crazy-max/ghaction-github-labeler@v5
        continue-on-error: true
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          yaml-file: .github/labels.yml
          dry-run: ${{ github.event_name == 'pull_request' }}
          exclude: |
            help*
            *issue