name: TriageOps - Labels Manager

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '.github/labels.yml'
      - '.github/workflows/labels.yml'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/labels.yml'
      - '.github/workflows/labels.yml'

jobs:
  labels-manager:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709
      - name: Download .env.ci from central repo
        run: wget -O .env.ci https://github.com/andreijiroh-dev/dotenvx-secretstore/raw/main/.env.ci
      - name: Load secrets via dotenvx
        uses: andreijiroh-dev/dotenvx-action@main
        with:
          path: .env.ci
          key: ${{ secrets.DOTENV_META_SECRETS_KEY_CI }}
        id: dotenvx
      - name: Sync labels using config
        uses: crazy-max/ghaction-github-labeler@24d110aa46a59976b8a7f35518cb7f14f434c916
        continue-on-error: true
        with:
          github-token: ${{ steps.dotenvx.outputs.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          dry-run: ${{ github.event_name == 'pull_request' }}
